version: "3.9"

services:
  # ==============================
  # Identity DB
  # ==============================
  identity-db:
    image: postgres:17.7
    container_name: identity-db
    environment:
      POSTGRES_DB: identitydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 2525
    ports:
      - "5433:5432" # Puerto PC -> contenedor
    volumes:
      - identity_data:/var/lib/postgresql/data
    networks:
      - mc-network

  # ==============================
  # Product / Catalog DB
  # ==============================
  product-db:
    image: postgres:17
    container_name: product-db
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 2525
    ports:
      - "5434:5432"
    volumes:
      - product_data:/var/lib/postgresql/data
    networks:
      - mc-network

  # ==============================
  # Order DB
  # ==============================
  order-db:
    image: postgres:17
    container_name: order-db
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 2525
    ports:
      - "5435:5432"
    volumes:
      - order_data:/var/lib/postgresql/data
    networks:
      - mc-network

  # ==============================
  # Identity Service
  # ==============================
  identity-service:
    build:
      context: ./Services/IdentityServices/IdentityServices
      dockerfile: Api/Dockerfile
    container_name: identity-service
    ports:
      - "5000:80"
    depends_on:
      - identity-db
    networks:
      - mc-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=identity-db;Port=5432;Database=identitydb;Username=user;Password=2525

  # ==============================
  # Product Service
  # ==============================
  product-service:
    build:
      context: ./Services/ProductServices/ProductServices
      dockerfile: Api/Dockerfile
    container_name: product-service
    ports:
      - "5001:80"
    depends_on:
      - product-db
    networks:
      - mc-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=product-db;Port=5432;Database=productdb;Username=user;Password=2525

  # ==============================
  # Order Service
  # ==============================
  order-service:
    build:
      context: ./Services/OrderServices/OrderServices
      dockerfile: Api/Dockerfile
    container_name: order-service
    ports:
      - "5002:80"
    depends_on:
      - order-db
    networks:
      - mc-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=order-db;Port=5432;Database=orderdb;Username=user;Password=2525

# ==============================
# Volúmenes persistentes
# ==============================
volumes:
  identity_data:
  product_data:
  order_data:

# ==============================
# Red de comunicación
# ==============================
networks:
  mc-network:
    driver: bridge
